import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import BackToTop from "./components/BackToTop";
import { Toaster } from "react-hot-toast";
import AuthProvider from "./components/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white">
        <Navbar/>
        <Toaster position="top-right" reverseOrder={false} />
        <AuthProvider>
          <div>
            {children}
          </div>
        </AuthProvider>
        <BackToTop/>
      </body>
    </html>
  );
}